grammar Flu;      
program: sentence;
sentence: verb (phrase)? (date)?;
verb: START| END| SHOW| PREDICT| ADD;
START: 'start'| 'Start';
END: 'End'| 'end';
SHOW: 'show'| 'Show';
PREDICT: 'predict'|'Predict';
ADD: 'Add'| 'add';
date: dateInNum | dateInWord;
dateInNum: DATE_MONTH SLASH DATE_MONTH SLASH YEAR;
SLASH : '/'|'-';
dateInWord: 'tomorrow'|'today'|'yesterday';
phrase: WORD+;
WORD: [a-z]+;
DATE_MONTH: INT | INT INT;
YEAR: INT INT INT INT;
INT: [0-9];
WS: [ \t\r\n]+ -> skip;
